program: train.py
command:
  - python
  - ${program}
  - "--config"
  - "configs/experiments/drive_mosin_base_config.yaml"
  - "--sweep"
  - "--folds"
  - 5
  - "--fold_no"
  - 4
  - "--integrate_test"
  - "--test_best"
name: fold5_drive_mosin_base
method: random
metric:
  goal: maximize
  name: val/best_combined_metric
run_cap: 25
parameters:
  alpha:
    distribution: log_uniform_values
    max: 0.01
    min: 0.0001
  lr:
    distribution: log_uniform_values
    max: 0.01
    min: 0.0001
  dice_type:
    values: ['dice']
  cldice_alpha:
    values: [-1]
  channels:
    values:
      - [16, 32, 64, 128, 256]
  num_res_units:
    values: [5]
  alpha_warmup_epochs:
    values: [20, 50, 80]
  one_vs_rest:
    values: [false]
  batch_size:
    values: [8, 16]
  aggregation_type:
    values: [none]
  thres_distr:
    values: [none]
  thres_var:
    values: [-1]
  lr_schedule:
    values: ['cosine_restarts']