MODEL:
  NAME: 'UNet'                     # Model name
  CHANNELS: [32, 64, 128, 256]
  NUM_RES_UNITS: 3

LOSS:
  USE_LOSS: 'Topograph'         # Avilable options 'Dice', 'ClDice', 'FastMulticlassDiceBettiMatching', 'HuTopo'
  ALPHA: 0.0015300567943913963
  DICE_TYPE: 'dice'          # Only relevant for "FastMulticlassDiceBettiMatching"
  CLDICE_ALPHA: -1
  ALPHA_WARMUP_EPOCHS: 20
  DIMENSIONS: [0,1]
  EIGHT_CONNECTIVITY: False

TRAIN:
  NUM_WORKERS: 16                   # Number of data loading threads
  SEED: 10                          # random seed for reproducibility
  MAX_EPOCHS: 300
  LR: 0.0007352981033659858
  BATCH_SIZE: 16                     # Batch size for a single GPU
  SAVE_PATH: "./models/"            # save path for the checkpoint
  LOG_PATH: "./runs/"               # save path for the tensorboard log
  VAL_INTERVAL: 5                   # validation interval
  LOG_INTERVAL: 1                  # wandb log interval
  LR_SCHEDULE: "cosine_restarts"

DATA:
  DIM: 2                                                        # data dimension
  DATA_PATH: "./data/cremi" # Path to dataset
  TEST_PATH: "./data/cremi_test" # Path to test-dataset
  DATASET: 'cremi'                                              # Dataset name
  IMG_SIZE: 256                                          # Input image size
  NUM_SAMPLES: -1                                                # Number of slices (=> this is not the number of samples because each slice is getting patched)
  IN_CHANNELS: 1
  OUT_CHANNELS: 2
  RESCALE: 1
  NUM_PATCH: 1
  FIVE_CROPS: False
  NORMALIZE: False
  INCLUDE_BACKGROUND: False
