MODEL:
  NAME: 'UNet'                     # Model name
  CHANNELS: [16, 32, 64, 128, 256]
  NUM_RES_UNITS: 5

LOSS:
  USE_LOSS: 'Topograph'         # Avilable options 'Dice', 'ClDice', 'FastMulticlassDiceBettiMatching', 'HuTopo'
  ALPHA: 0.0005
  DICE_TYPE: 'dice'          # Only relevant for "FastMulticlassDiceBettiMatching"
  CLDICE_ALPHA: -1
  ALPHA_WARMUP_EPOCHS: 60
  DIMENSIONS: [0,1]
  ONE_VS_REST: True
  PUSH_UNMATCHED_TO_1_0: True
  BARCODE_LENGTH_THRESHOLD: 0.0
  EIGHT_CONNECTIVITY: True

TRAIN:
  NUM_WORKERS: 16                   # Number of data loading threads
  SEED: 10                          # random seed for reproducibility
  MAX_EPOCHS: 400
  LR: 0.0002
  BATCH_SIZE: 8                     # Batch size for a single GPU
  SAVE_PATH: "./models/"            # save path for the checkpoint
  LOG_PATH: "./runs/"               # save path for the tensorboard log
  VAL_INTERVAL: 5                   # validation interval
  LOG_INTERVAL: 1                  # wandb log interval
  LR_SCHEDULE: "cosine_restarts"

DATA:
  DIM: 2                                                        # data dimension
  DATA_PATH: "./data/DRIVE/training" # Path to dataset
  TEST_PATH: "./data/DRIVE/test" # Path to test-dataset
  DATASET: 'drive'                                              # Dataset name
  IMG_SIZE: 256                                          # Input image size
  NUM_SAMPLES: -1                                                # Number of slices (=> this is not the number of samples because each slice is getting patched)
  IN_CHANNELS: 3
  OUT_CHANNELS: 2
  RESCALE: 1
  NUM_PATCH: 1
  FIVE_CROPS: False
  NORMALIZE: False
  INCLUDE_BACKGROUND: False
  FILL_HOLE: False