program: train.py
command:
  - python
  - ${program}
  - "--config"
  - "configs/experiments/cremi_hutopo_config.yaml"
  - "--sweep"
  - "--folds"
  - 5
  - "--fold_no"
  - 2
  - "--integrate_test"
  - "--test_best"
name: fold3_cremi_hutopo
method: random
metric:
  goal: maximize
  name: val/best_combined_metric
run_cap: 25
parameters:
  alpha:
    distribution: log_uniform_values
    max: 0.02
    min: 0.00001
  lr:
    distribution: log_uniform_values
    max: 0.01
    min: 0.0001
  dice_type:
    values: ['dice']
  cldice_alpha:
    values: [-1]
  channels:
    values:
      - [32, 64, 128, 256]
      - [32, 64, 128, 256, 512]
      - [16, 32, 64, 128]
      - [16, 32, 64, 128, 256]
  num_res_units:
    values: [3, 4, 5]
  alpha_warmup_epochs:
    values: [20, 50, 80]
  one_vs_rest:
    values: [false]
  batch_size:
    values: [8, 16, 32]
  aggregation_type:
    values: [mean]
  thres_distr:
    values: [gaussian]
  thres_var:
    values: [0.0]
  lr_schedule:
    values: ['cosine_restarts']
  
